services:
  postgres:
    container_name: postgres-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: blogosphere
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - app-network
    restart: unless-stopped

  spring-boot:
    build: .
    container_name: spring-boot
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/blogosphere
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
    driver: local